name: 'git2jamf'
description: >
    creates, updates and delets scripts in jamf from your github repository
inputs:
    jamf_url:
        description: 'url of your jamf instance'
        required: true
    jamf_username:
        description: 'username to auth against jamf'
        required: true
    jamf_password:
        description: 'password to auth against jamf'
        required: true
    jamf_auth_type:
        description: 'auth for traditional username/pwd or oauth for clientid an secret'
        default: auth
    script_dir:
        description: >
            the directory where the scripts to process are defaults to the github.workspace environment variable
        default: ${{ github.workspace }}
    ea_script_dir:
        description: >
            the directory where the extion attribute scripts to process are defaults to the github.workspace environment variable
        default: false
    script_extensions:
        description: >
            extension for the types of scripts we'll be looking to upload defaults to .sh and .py files
        default: 'sh py'
    prefix:
        description: >
            Use the branch name as a prefix
        default: false
    delete:
        description: >
            Should we delete scripts that are not in github? Careful when turning this on!
        default: false


runs:
    using: 'docker'
    image: 'Dockerfile'
branding:
    color: purple
    icon: link
